tasks:
  - init: |
      python -m pip install --upgrade pip
      python -m pip install kafka-python
      python -m pip install pylint
      rm -rf producer
    command: |
      python main.py

vscode:
  extensions:
    - ms-python.python