image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      pip3 install --upgrade pip
      pip3 install kafka-python
      pip3 install pylint
      rm -rf producer
    command: |
      python main.py

vscode:
  extensions:
    - ms-python.python